FROM debian:bookworm

# ------ Build and install dependencies ------

ARG LLVM_V=19

# Add the LLVM apt repo
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates gnupg lsb-release software-properties-common wget && \
  wget https://apt.llvm.org/llvm.sh && \
  chmod +x llvm.sh && \
  ./llvm.sh ${LLVM_V}

# Install LLVM toolchain & deps for AFL++, Nyx, Bitcoin Core
# vim & tmux are useful
RUN apt-get update && apt install -y --no-install-recommends \
  ninja-build \
  libgtk-3-dev \
  pax-utils \
  python3-msgpack \
  python3-jinja2 \
  curl \
  lld-${LLVM_V} \
  llvm-${LLVM_V} \
  llvm-${LLVM_V}-dev \
  clang-${LLVM_V} \
  cpio \
  git \
  build-essential \
  libtool \
  autotools-dev \
  automake \
  cmake \
  pkg-config \
  bsdmainutils \
  openssh-client \
  libcapstone-dev \
  python3 \
  libzstd-dev \
  libssl-dev \
  tmux \
  vim \
  gnuplot

# Install rust and tools
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup install nightly && rustup default nightly
RUN cargo install cargo-afl

WORKDIR /
# Clone AFLplusplus and build
ENV LLVM_CONFIG=llvm-config-${LLVM_V}
RUN git clone https://github.com/AFLplusplus/AFLplusplus
RUN cd AFLplusplus && make PERFORMANCE=1 -j$(nproc --ignore 1)

# ------ Build Bitcoin Core and the nyx agent ------

# Build Bitcoin Core
ARG OWNER=bitcoin
ARG REPO=bitcoin
ARG BRANCH=master
ARG PR_NUMBER=
ARG BITCOIN_COMMIT=""

RUN git clone --depth 1 --branch "${BRANCH}" "https://github.com/${OWNER}/${REPO}.git" "${REPO}" && \
    cd "${REPO}" && \
    if [ -n "${PR_NUMBER}" ]; then \
        git fetch --depth 1 origin "pull/${PR_NUMBER}/head:pr-${PR_NUMBER}" && \
        git checkout "pr-${PR_NUMBER}"; \
    elif [ -n "${BITCOIN_COMMIT}" ]; then \
        git fetch --depth 1 origin "${BITCOIN_COMMIT}" && \
        git checkout "${BITCOIN_COMMIT}"; \
    fi

ENV CC=/AFLplusplus/afl-clang-fast
ENV CXX=/AFLplusplus/afl-clang-fast++
ENV LD=/AFLplusplus/afl-clang-fast

COPY ./target-patches/bitcoin-core-ir-denylist.txt /denylist.txt
ENV AFL_LLVM_DENYLIST=/denylist.txt

ENV SOURCES_PATH=/tmp/bitcoin-depends
RUN make -C bitcoin/depends NO_QT=1 NO_ZMQ=1 NO_USDT=1 download-linux SOURCES_PATH=$SOURCES_PATH
# Keep extracted source
RUN sed -i --regexp-extended '/.*rm -rf .*extract_dir.*/d' ./bitcoin/depends/funcs.mk && \
    make -C ./bitcoin/depends DEBUG=1 NO_QT=1 NO_ZMQ=1 NO_USDT=1 \
      SOURCES_PATH=$SOURCES_PATH \
      AR=llvm-ar-${LLVM_V} NM=llvm-nm-${LLVM_V} RANLIB=llvm-ranlib-${LLVM_V} STRIP=llvm-strip-${LLVM_V} \
      -j$(nproc)

COPY ./target-patches/bitcoin-core-aggressive-rng.patch bitcoin/
RUN cd bitcoin/ && \
      git apply bitcoin-core-aggressive-rng.patch

ARG BUG_PATCH
ARG DIFFERENTIAL=0

COPY ./bugs /bugs

# apply BUG_PATCH immediately if not in differential mode
RUN cd bitcoin/ && \
    if [ "${DIFFERENTIAL}" != "1" ] && [ -n "${BUG_PATCH}" ]; then \
        patch_path="/bugs/${BUG_PATCH}/bug.diff"; \
        test -f "${patch_path}"; \
        git apply "${patch_path}" || exit 1; \
    fi

RUN cd bitcoin/ && cmake -B build_fuzz \
      --toolchain ./depends/$(./depends/config.guess)/toolchain.cmake \
      -DSANITIZERS="address" \
      -DAPPEND_CPPFLAGS="-DFUZZAMOTO_FUZZING -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -DABORT_ON_FAILED_ASSUME" \
      -DAPPEND_LDFLAGS="-fuse-ld=lld-${LLVM_V}"

# first build
RUN cmake --build bitcoin/build_fuzz -j$(nproc) --target bitcoind

# second build for the modified target
RUN cd bitcoin/ && \
    if [ "${DIFFERENTIAL}" = "1" ] && [ -n "${BUG_PATCH}" ]; then \
        cp -f build_fuzz/bin/bitcoind build_fuzz/bin/bitcoind_reference; \
        patch_path="/bugs/${BUG_PATCH}/bug.diff"; \
        test -f "${patch_path}"; \
        git apply "${patch_path}" || exit 1; \
        cmake --build build_fuzz -j$(nproc) --target bitcoind; \
    fi

ENV CC=clang-${LLVM_V}
ENV CXX=clang++-${LLVM_V}
ENV LD=lld-${LLVM_V}

# Needed to avoid "fatal: detected dubious ownership in repository" errors from
# the Nyx build inside of target/
RUN git config --global --add safe.directory /fuzzamoto
